language: julia
os:
  - linux
  - osx
julia: 
  - 1.0
  - nightly
matrix:
  allow_failures:
    - os: osx

notifications:
  - email: false
script:
  - julia -e "using Pkg; if VERSION >= v\"1.1.0-rc1\"; Pkg.build(verbose=true); else Pkg.build(); end;"
  - julia -e 'using Pkg; Pkg.test("LatticeGFH90");'
